server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:60741;databaseName=PESSOA_DB;user=sa;password=162243
    username: sa
    password: 162243
  jpa:
    show-sql: true 
    properties:
      hibernate:
        format_sql: true
